Fix #283. Jira API V2 is expecting a 'name' property
ahungry/org-jira pull request #304
Opened 2022-07-21 10:11 UTC by jeromeag

This fix is needed for Tickets updates with a recent Jira server.
(naive copy/paste from [pjgarcia](https://github.com/pjgarcia) comment in #283) 
I don't know if this fix is working also on legacy Jira servers.
Maybe it is needed to test Jira API version to implement a better fix.

2022-07-22 14:53 UTC, ahungry commented on jiralib.el
>  (defun jiralib-get-user-account-id (project full-name)
I didn't test it - the change looks good, but leaves the function name as a misnomer - if it's no longer returning an account-id, it should be changed (or left alone, and a new one added) called `jiralib-get-user-name` or similar.

2022-07-22 14:53 UTC, ahungry requested changes
See comment

2022-07-23 15:40 UTC, ahungry commented
You mention api v2, which I assume based on a comment here: https://github.com/ahungry/org-jira/issues/305 is the API version tied to your on prem jira version.

Work was done awhile ago to ensure account-id worked instead of name, for various things (like assignee/reporter id) - this change seems to go in the opposite direction, and I'm wondering how compatible it is with jira cloud/v3 api - can someone with cloud access please test the changes out?

I checked their docs now, and the REST docs are pretty unreadable atm (supposed to be dynamic or something, and instead of listing out the params, they have "meta" endpoints to do it now) - the couple searches I did for account-id now seem to imply account-id and name are interchangeable things.

I know cloud jira descriptions quit support name type tagging like `[~mcarter]` some time ago, in favor of long uuid (account-id) values.

2022-07-23 15:53 UTC, jeromeag commented
At first, I mentioned api v2 based on a comment here [ issue 283](https://github.com/ahungry/org-jira/issues/283#issuecomment-1047925882).
The proposed fix worked for me... and I have done a PR expecting (naively) the fix to be included the next release.

It seems that a more complete fix would be to first check the API version.
I'm afraid that my elisp/rest skills wil not be sufficient.

2022-07-23 15:57 UTC, ahungry commented
At some point I made an org-jira-sdk abstraction to encapsulate the field values of the various REST entities (issue / comment / board) - I wonder if doing some type of dispatch/multimethod based on a user setting for "remote api version" (or maybe we can set that dynamically) would allow the code to have a linear flow, while still supporting multiple versions/hosting solutions of jira.  In the past, I had to postpone merge on some "on-prem" changes, as they didn't work (or were untested) against the cloud version.

What's the minimal acceptance test/outline of a scenario to produce the failure and subsequent fix your PR addresses?

Something like:

- File an issue with org-jira-create-issue
- Observe the assignee/reporter are failed to be set

2022-07-23 17:27 UTC, jeromeag commented
Without this modification the **org-jira-update-issue** call was simply failing with "expected Object containing a 'name' property" Jira server error. (I googled it and felt on #283 issue event if the way to get the error is not the same).

So to reproduce:
- update an issue with org-jira-update-issue
- observe: 
> "JIRA_ERROR RESPONSE: "
> ((errorMessages . []) (errors (assignee . "expected Object containing a 'name' property")))

2022-07-23 23:06 UTC, ahungry commented
I tested this out on the cloud - name isn't a valid piece of the assignee object - it defers to accountId - I think a couple people may be keeping their own customized fork for working with on-prem jiras - as (I believe) cloud is the most common jira option (certainly the most up to date one) I want to keep that as the main target, so I'll have to pass on this PR for now - thank you though - it would be a good reference if I plan to add non-cloud support targets.

2022-07-23 23:06 UTC, closed without merging